name: hedgehog
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.8.8
  - pandas=1.2.4
  - tqdm=4.49
  - pytorch=1.8.1
  - cudatoolkit=10.2.89
  - scikit-learn=0.23.2
  - requests=2.25.1
  - tensorboardx=2.2
  - wandb=0.10.30
  - pip=21.0.1
  - pip:
      - simpletransformers=0.61.4
